name: lit_ui_kit
version: 1.0.4
homepage: https://github.com/litlifesoftware/lit_ui_kit
description: >-
  Contains a collection of code implementing the Lit UI design language.
  It provides several widgets and screens in addition to custom model 
  classes and controller classes for easier use.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^2.0.2
  url_launcher: ^6.0.6
  intl: ^0.17.0

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/Plain_Logo_Small.png
    - assets/images/Plain_Logo.png
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LitIcons
      fonts:
        - asset: assets/icons/LitIcons.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Black.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Light.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323/VT323-Regular.ttf
  # - family: Trajan Pro
  #   fonts:
  #     - asset: fonts/TrajanPro.ttf
  #     - asset: fonts/TrajanPro_Bold.ttf
  #       weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
